workspace(name = "simple_example")

local_repository(
    name = "cgrindel_rules_updatesrc",
    path = "../..",
)

load("@cgrindel_rules_updatesrc//updatesrc:deps.bzl", "updatesrc_rules_dependencies")

updatesrc_rules_dependencies()

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()
